const dummyData = {
  colors: ["#f7d050", "#a6e3ed", "#f7d050"],
  Projects: [
    {
      projectId: 1,
      title: "Physics Project For Today",
      percentage: "55",
      subject: "Physics",
      description: "Simple project deployed for the help of thi",
      dueDate: "12/15/2029",
      count: 0,
    },
    {
      projectId: 2,
      title: "Mathematics Project Project For Today",
      percentage: "55",
      subject: "Mathematics",
      description: "Simple project deployed for the help of thi",
      dueDate: "12/15/2020",
      count: 1,
    },
    {
      projectId: 3,
      title: "Mathematics Project Project For Today",
      percentage: "55",
      subject: "Mathematics",
      description: "Simple project deployed for the help of thi",
      dueDate: "12/15/2020",
      count: 1,
    },
  ],
  Todos: [
    {
      title: "Finish Doung my Homework",
      subject: "Physics",
      type: "Assignment",
      professor: "Frederic Rodrigez",
      time: "12:45 AM",
      dueDate: "05/07/2020",
      done: true,
    },
    {
      title: "Finish Doung my Homework",
      subject: "Computer Science",
      type: "Assignment",
      professor: "Felix Amoruwa",
      time: "12:45 AM",
      dueDate: "05/07/2020",
      done: false,
      highlighted: true,
    },
    {
      title: "Finish Doung my Homework",
      subject: "Physics",
      type: "Assignment",
      professor: "Frederic Rodrigez",
      time: "12:45 AM",
      dueDate: "05/07/2020",
      done: false,
    },
    {
      title: "Finish Doung my Homework",
      subject: "Physics",
      type: "Assignment",
      professor: "Frederic Rodrigez",
      time: "12:45 AM",
      dueDate: "05/07/2020",
      done: false,
    },
  ],
  Exams: [
    {
      title: "Physics",
      day: "Tue",
      professor: "Felix A",
      time: "12:24pm",
      first: true,
    },
    {
      title: "Mathematics",
      day: "Thu",
      professor: "Gorilla L",
      time: "8:54am",
    },
    {
      title: "Computer Science",
      day: "Thu",
      professor: "Gorilla L",
      time: "8:54am",
    },
  ],
};
export default dummyData;
